# Generated by Django 6.0.2 on 2026-02-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'External Link')], default='image', max_length=10),
        ),
    ]
